import Link from 'next/link'
import Image from 'next/image'
import type { Metadata } from 'next'
import { HomeHero } from '@/components/home-hero'
import { CommunityCarousel } from '@/components/community-carousel'
import { getHomeContent } from '@/sanity/lib/queries'

const hasText = (...values: Array<string | undefined>) => values.some((value) => Boolean(value?.trim()))
const nonEmpty = (value: string) => Boolean(value.trim())

export default async function HomePage() {
  const content = await getHomeContent()
  const leadership = content.leadership
  const principal = content.principal
  const notice = content.notice
  const community = content.community
  const viewpoint = content.viewpoint
  const hasLeadership = hasText(leadership.label, leadership.title, leadership.accent, leadership.image, leadership.signoff, leadership.name, leadership.role) || leadership.paragraphs.some(nonEmpty)
  const hasPrincipal = hasText(principal.label, principal.title, principal.accent, principal.mission, principal.quoteLead, principal.quote, principal.image, principal.signoff, principal.name, principal.qualifications) || principal.leftParagraphs.some(nonEmpty) || principal.rightParagraphs.some(nonEmpty)
  const hasNotice = hasText(notice.label, notice.eventLabel, notice.title, notice.summary, notice.updatedAt, notice.viewMoreLabel, notice.viewMoreHref)
  const hasCommunity = hasText(community.title, community.subtitle, community.image, community.imageAlt) || community.gallery.length > 0
  const hasViewpoint = hasText(viewpoint.label, viewpoint.title, viewpoint.accent, viewpoint.lead, viewpoint.body)

  return <main>
    <HomeHero content={content} />

    {hasLeadership && <section className="bg-cream py-8 sm:py-12"><div className="site-shell grid gap-12 lg:grid-cols-[342px_726px] lg:gap-20"><div>{hasText(leadership.label) && <p className="section-label">{leadership.label}</p>}{hasText(leadership.title, leadership.accent) && <h2 className="mt-8 max-w-[342px] font-display text-4xl font-bold leading-[.95] tracking-[-.07em] text-ink sm:text-5xl lg:text-[2.85rem]">{leadership.title}{hasText(leadership.accent) && <em className="mt-2 block whitespace-nowrap font-serif text-[2.25rem] font-normal leading-[.9] tracking-[-.05em] text-[#6d9d8b] sm:text-4xl lg:text-[2.25rem]">{leadership.accent}</em>}</h2>}{leadership.image && <div className="relative mt-12 aspect-[2/3] max-w-[37rem] overflow-hidden bg-paper"><Image src={leadership.image} alt={leadership.imageAlt ?? ''} fill sizes="(min-width: 1024px) 40vw, 100vw" className="object-cover object-center" /></div>}</div>{leadership.paragraphs.some(nonEmpty) || hasText(leadership.signoff, leadership.name, leadership.role) ? <div className="max-w-4xl space-y-8 pt-1 text-lg leading-[1.75] text-ink-soft sm:text-xl">{leadership.paragraphs.filter(nonEmpty).map((paragraph, index) => <p key={`${index}-${paragraph.slice(0, 12)}`} className={index === 0 ? 'text-ink' : undefined}>{paragraph}</p>)}{hasText(leadership.signoff, leadership.name, leadership.role) && <div className="border-t border-ink/15 pt-7">{hasText(leadership.signoff) && <p className="font-serif text-2xl text-ink">{leadership.signoff}</p>}{hasText(leadership.name) && <p className="mt-4 font-display text-xl font-bold text-ink">{leadership.name}</p>}{hasText(leadership.role) && <p className="mt-1 text-sm font-semibold text-ink-soft">{leadership.role}</p>}</div>}</div> : null}</div></section>}

    {hasPrincipal && <section className="bg-paper py-8 sm:py-12"><div className="site-shell"><div className="grid items-stretch gap-10 lg:grid-cols-[1.35fr_.85fr] lg:gap-20"><div>{hasText(principal.label) && <p className="section-label">{principal.label}</p>}{hasText(principal.title, principal.accent) && <h2 className="mt-8 font-display text-4xl font-bold leading-[.94] tracking-[-.07em] text-ink sm:text-5xl">{principal.title} {hasText(principal.accent) && <em className="font-serif font-normal text-lime">{principal.accent}</em>}</h2>}{hasText(principal.mission) && <p className="mt-10 max-w-3xl font-serif text-2xl leading-tight text-ink sm:text-3xl">{principal.mission}</p>}{hasText(principal.quoteLead) && <p className="mt-10 font-serif text-2xl text-ink-soft">{principal.quoteLead}</p>}{hasText(principal.quote) && <blockquote className="mt-6 max-w-4xl font-serif text-3xl leading-[1.12] tracking-[-.045em] text-ink sm:text-4xl">{principal.quote}</blockquote>}</div>{principal.image && <div className="relative min-h-[22rem] overflow-hidden bg-cream lg:min-h-0"><Image src={principal.image} alt={principal.imageAlt ?? ''} fill sizes="(min-width: 1024px) 35vw, 100vw" className="object-cover object-center" /></div>}</div>{principal.leftParagraphs.some(nonEmpty) || principal.rightParagraphs.some(nonEmpty) || hasText(principal.signoff, principal.name, principal.qualifications) ? <div className="mt-10 grid gap-8 border-t border-ink/15 pt-8 text-lg leading-relaxed text-ink-soft md:grid-cols-2 md:gap-16"><div className="space-y-6">{principal.leftParagraphs.filter(nonEmpty).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><div className="space-y-6">{principal.rightParagraphs.filter(nonEmpty).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{hasText(principal.signoff, principal.name, principal.qualifications) && <div className="pt-2 text-ink">{hasText(principal.signoff) && <p className="font-serif text-2xl">{principal.signoff}</p>}{hasText(principal.name) && <p className="mt-4 font-display text-lg font-bold">{principal.name}</p>}{hasText(principal.qualifications) && <p className="mt-1 text-sm font-semibold text-ink-soft">{principal.qualifications}</p>}</div>}</div></div> : null}</div></section>}

    {(hasNotice || hasCommunity) && <section className="bg-ink-deep py-10 text-ink sm:py-14"><div className="site-shell grid gap-5 lg:grid-cols-[1fr_.9fr] lg:gap-5">{hasNotice && <article className="min-h-[31rem] border-[6px] border-[#bda372] bg-paper p-8 sm:p-12">{hasText(notice.label) && <h2 className="section-heading !mt-0 text-[#8b713e]">{notice.label}</h2>}{hasText(notice.eventLabel) && <div className="mt-7 flex border-b border-[#d2b97e]"><span className="rounded-t-[2rem] bg-[#bda372] px-9 py-4 text-lg font-medium text-white">{notice.eventLabel}</span><span className="rounded-t-[2rem] bg-[#cdb68c] px-9 py-4 text-lg font-medium text-white">Event</span></div>}{hasText(notice.title, notice.summary, notice.updatedAt) && <div className="relative mt-10 border-l-4 border-ink/40 pl-10"><span className="absolute -left-[13px] top-0 h-6 w-6 rounded-full border-[5px] border-white bg-sky-400 shadow-[0_0_0_2px_#38bdf8]" aria-hidden="true" />{hasText(notice.title) && <h3 className="text-2xl font-bold text-ink">{notice.title}</h3>}{hasText(notice.summary) && <p className="mt-6 max-w-xl text-lg leading-relaxed text-ink-soft">{notice.summary}</p>}{hasText(notice.updatedAt) && <p className="mt-5 text-sm font-medium text-[#9a5db4]">Updated on: {notice.updatedAt}</p>}</div>}{hasText(notice.viewMoreLabel, notice.viewMoreHref) && <Link href={notice.viewMoreHref} className="mt-8 inline-flex rounded-r-full rounded-l-md bg-[#bda372] px-8 py-4 text-lg font-medium text-white transition hover:bg-[#a88b57]">{notice.viewMoreLabel} <span className="ml-8" aria-hidden="true">→</span></Link>}</article>}{hasCommunity && <article className="overflow-hidden rounded-tr-[6rem] border-[6px] border-[#bda372] bg-paper p-8 sm:p-10">{community.gallery.length > 0 && <CommunityCarousel items={community.gallery} />}{hasText(community.title, community.subtitle) && <div className="bg-[#edf3ee] px-7 py-6 text-center">{hasText(community.title) && <h3 className="font-display text-3xl font-bold tracking-[-.05em] text-[#6f5931]">{community.title}</h3>}{hasText(community.subtitle) && <p className="mt-2 text-lg font-medium text-ink-soft">{community.subtitle}</p>}</div>}</article>}</div></section>}

    {hasViewpoint && <section className="bg-paper py-8 sm:py-12"><div className="site-shell grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:gap-24"><div>{hasText(viewpoint.label) && <p className="section-label">{viewpoint.label}</p>}{hasText(viewpoint.title, viewpoint.accent) && <h2 className="section-heading">{viewpoint.title} {hasText(viewpoint.accent) && <em>{viewpoint.accent}</em>}</h2>}</div>{hasText(viewpoint.lead, viewpoint.body) && <div className="text-lg leading-relaxed text-ink-soft">{hasText(viewpoint.lead) && <p className="text-xl text-ink">{viewpoint.lead}</p>}{hasText(viewpoint.body) && <p className="mt-5">{viewpoint.body}</p>}</div>}</div></section>}

    {content.highlights.length > 0 && <section className="bg-cream py-8 sm:py-12"><div className="site-shell"><p className="section-label">Explore GDIS</p><h2 className="section-heading mb-10">Every path starts with a <em>question.</em></h2><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{content.highlights.filter((item) => hasText(item.title, item.body, item.href)).map((item, index) => <Link key={`${item.href}-${item.title}`} href={item.href} className="group min-h-58 border border-ink/15 bg-white/45 p-7 transition hover:-translate-y-1 hover:bg-white"><span className="text-xs font-extrabold tracking-[0.14em] text-ink-soft">0{index + 1}</span>{hasText(item.title) && <h3 className="mt-12 font-display text-2xl font-bold tracking-[-0.04em]">{item.title}</h3>}{hasText(item.body) && <p className="mt-3 leading-relaxed text-ink-soft">{item.body}</p>}<span className="mt-5 inline-block font-bold text-olive transition group-hover:translate-x-1">Explore →</span></Link>)}</div></div></section>}
  </main>
}

export async function generateMetadata(): Promise<Metadata> {
  const content = await getHomeContent()
  return { title: content.seoTitle ?? 'Home', description: content.seoDescription }
}
