import Link from 'next/link'
import Image from 'next/image'
import type { MarketingPageContent } from '@/lib/site-content'
import type { FacultyMember } from '@/sanity/lib/queries'

const hasText = (...values: Array<string | undefined>) => values.some((value) => Boolean(value?.trim()))

export function MarketingPage({ content, faculty }: { content: MarketingPageContent; faculty?: FacultyMember[] }) {
  const hasHero = hasText(content.eyebrow, content.heroTitle, content.heroAccent, content.heroSummary) || Boolean(content.heroImage?.url)
  const hasIntro = hasText(content.introLabel, content.introTitle, content.introAccent) || content.introBody.length > 0
  const hasFeatures = hasText(content.featureLabel, content.featureTitle, content.featureAccent) || content.cards.length > 0
  const hasPanel = hasText(content.panelLabel, content.panelTitle, content.panelAccent, content.panelHeading, content.panelBody) || content.panelItems.length > 0
  const hasCta = hasText(content.cta, content.ctaAccent, content.ctaLabel, content.ctaHref)

  return <main>
    {hasHero && <section className="relative overflow-hidden bg-ink py-20 text-white sm:py-28">
      {content.heroImage?.url && <><Image src={content.heroImage.url} alt={content.heroImage.alt ?? ''} fill priority sizes="100vw" className="object-cover opacity-35" /><div className="absolute inset-0 bg-ink/55" /></>}
      <div className="absolute -right-24 -bottom-60 h-[42rem] w-[42rem] rounded-full border border-lime/20" />
      <div className="site-shell relative">{hasText(content.eyebrow) && <p className="eyebrow text-white/65">{content.eyebrow}</p>}{hasText(content.heroTitle, content.heroAccent) && <h1 className="mt-6 max-w-5xl font-display text-5xl font-bold tracking-[-0.07em] sm:text-7xl lg:text-8xl">{content.heroTitle}{hasText(content.heroAccent) && <><br /><em className="font-serif font-normal text-lime">{content.heroAccent}</em></>}</h1>}{hasText(content.heroSummary) && <p className="mt-6 max-w-2xl text-lg leading-relaxed text-white/75 sm:text-xl">{content.heroSummary}</p>}</div>
    </section>}

    {hasIntro && <section className="bg-paper py-16 sm:py-24"><div className="site-shell grid gap-10 lg:grid-cols-[0.75fr_1.25fr] lg:gap-24"><div>{hasText(content.introLabel) && <p className="section-label">{content.introLabel}</p>}{hasText(content.introTitle, content.introAccent) && <h2 className="section-heading">{content.introTitle} {hasText(content.introAccent) && <em>{content.introAccent}</em>}</h2>}</div>{content.introBody.length > 0 && <div className="space-y-5 text-lg leading-relaxed text-ink-soft">{content.introBody.filter((paragraph) => paragraph.trim()).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div>}</div></section>}

    {hasFeatures && <section className="bg-cream py-16 sm:py-24"><div className="site-shell">{hasText(content.featureLabel) && <p className="section-label">{content.featureLabel}</p>}{hasText(content.featureTitle, content.featureAccent) && <h2 className="section-heading mb-10">{content.featureTitle} {hasText(content.featureAccent) && <em>{content.featureAccent}</em>}</h2>}{content.cards.length > 0 && <div className="grid gap-5 md:grid-cols-3">{content.cards.filter((card) => hasText(card.number, card.title, card.body) || Boolean(card.image?.url)).map((card) => <article key={card.title} className="min-h-60 overflow-hidden border border-ink/15 bg-white/45">{card.image?.url && <div className="relative aspect-[16/9]"><Image src={card.image.url} alt={card.image.alt ?? ''} fill sizes="(min-width: 768px) 33vw, 100vw" className="object-cover" /></div>}<div className="p-7">{hasText(card.number) && <p className="mb-12 text-xs font-extrabold tracking-[0.14em] text-ink-soft">{card.number}</p>}{hasText(card.title) && <h3 className="font-display text-2xl font-bold tracking-[-0.04em]">{card.title}</h3>}{hasText(card.body) && <p className="mt-3 leading-relaxed text-ink-soft">{card.body}</p>}</div></article>)}</div>}</div></section>}

    {faculty?.length ? <section className="bg-paper py-16 sm:py-24"><div className="site-shell"><p className="section-label">Meet the team</p><h2 className="section-heading mb-10">The people behind <em>the learning.</em></h2><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{faculty.filter((member) => hasText(member.name, member.role, member.qualifications, member.bio) || Boolean(member.photo?.url)).map((member) => <article key={`${member.name}-${member.role}`} className="overflow-hidden border border-ink/15 bg-[#fffdf7]">{member.photo?.url && <div className="relative aspect-[4/3]"><Image src={member.photo.url} alt={member.photo.alt ?? member.name} fill sizes="(min-width: 1024px) 33vw, 100vw" className="object-cover" /></div>}<div className="p-7">{hasText(member.name) && <h3 className="font-display text-2xl font-bold tracking-[-0.04em]">{member.name}</h3>}{hasText(member.role) && <p className="mt-2 font-medium text-olive">{member.role}</p>}{hasText(member.qualifications) && <p className="mt-3 text-sm text-ink-soft">{member.qualifications}</p>}{hasText(member.bio) && <p className="mt-4 leading-relaxed text-ink-soft">{member.bio}</p>}</div></article>)}</div></div></section> : null}

    {hasPanel && <section className="bg-paper py-16 sm:py-24"><div className="site-shell grid gap-10 lg:grid-cols-[0.75fr_1.25fr] lg:gap-24"><div>{hasText(content.panelLabel) && <p className="section-label">{content.panelLabel}</p>}{hasText(content.panelTitle, content.panelAccent) && <h2 className="section-heading">{content.panelTitle} {hasText(content.panelAccent) && <em>{content.panelAccent}</em>}</h2>}</div>{(hasText(content.panelHeading, content.panelBody) || content.panelItems.length > 0) && <div className="border border-ink/15 bg-[#fffdf7] p-8 sm:p-12">{hasText(content.panelHeading) && <h3 className="font-display text-3xl font-bold tracking-[-0.05em]">{content.panelHeading}</h3>}{hasText(content.panelBody) && <p className="mt-4 text-lg leading-relaxed text-ink-soft">{content.panelBody}</p>}{content.panelItems.length > 0 && <div className="mt-8 grid gap-5 sm:grid-cols-2">{content.panelItems.filter((item) => hasText(item.title, item.body) || Boolean(item.image?.url)).map((item) => <div key={item.title} className="border-t border-ink/15 pt-4">{hasText(item.title) && <strong className="block">{item.title}</strong>}{hasText(item.body) && <span className="mt-1 block text-sm leading-relaxed text-ink-soft">{item.body}</span>}</div>)}</div>}</div>}</div></section>}

    {hasCta && <section className="bg-ink-deep py-16 text-white sm:py-20"><div className="site-shell flex flex-col items-start justify-between gap-8 lg:flex-row lg:items-center">{hasText(content.cta, content.ctaAccent) && <h2 className="max-w-3xl font-display text-4xl font-bold tracking-[-0.06em] sm:text-6xl">{content.cta} {hasText(content.ctaAccent) && <em className="font-serif font-normal text-lime">{content.ctaAccent}</em>}</h2>}{hasText(content.ctaLabel, content.ctaHref) && <Link href={content.ctaHref} className="rounded-full bg-lime px-6 py-4 text-sm font-bold text-ink transition hover:-translate-y-0.5">{content.ctaLabel} →</Link>}</div></section>}
  </main>
}
