import Link from 'next/link'
import Image from 'next/image'
import type { MarketingPageContent } from '@/lib/site-content'
import type { FacultyMember } from '@/sanity/lib/queries'

export function MarketingPage({ content, faculty }: { content: MarketingPageContent; faculty?: FacultyMember[] }) {
  return (
    <main>
      <section className="relative overflow-hidden bg-ink py-20 text-white sm:py-28">{content.heroImage?.url && <><Image src={content.heroImage.url} alt={content.heroImage.alt ?? ''} fill priority sizes="100vw" className="object-cover opacity-35" /><div className="absolute inset-0 bg-ink/55" /></>}<div className="absolute -right-24 -bottom-60 h-[42rem] w-[42rem] rounded-full border border-lime/20" /><div className="site-shell relative"><p className="eyebrow text-white/65">{content.eyebrow}</p><h1 className="mt-6 max-w-5xl font-display text-5xl font-bold tracking-[-0.07em] sm:text-7xl lg:text-8xl">{content.heroTitle}<br /><em className="font-serif font-normal text-lime">{content.heroAccent}</em></h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-white/75 sm:text-xl">{content.heroSummary}</p></div></section>
      <section className="bg-paper py-16 sm:py-24"><div className="site-shell grid gap-10 lg:grid-cols-[0.75fr_1.25fr] lg:gap-24"><div><p className="section-label">{content.introLabel}</p><h2 className="section-heading">{content.introTitle} <em>{content.introAccent}</em></h2></div><div className="space-y-5 text-lg leading-relaxed text-ink-soft">{content.introBody.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div></section>
      <section className="bg-cream py-16 sm:py-24"><div className="site-shell"><p className="section-label">{content.featureLabel}</p><h2 className="section-heading mb-10">{content.featureTitle} <em>{content.featureAccent}</em></h2><div className="grid gap-5 md:grid-cols-3">{content.cards.map((card) => <article key={card.title} className="min-h-60 overflow-hidden border border-ink/15 bg-white/45">{card.image?.url && <div className="relative aspect-[16/9]"><Image src={card.image.url} alt={card.image.alt ?? ''} fill sizes="(min-width: 768px) 33vw, 100vw" className="object-cover" /></div>}<div className="p-7"><p className="mb-12 text-xs font-extrabold tracking-[0.14em] text-ink-soft">{card.number}</p><h3 className="font-display text-2xl font-bold tracking-[-0.04em]">{card.title}</h3><p className="mt-3 leading-relaxed text-ink-soft">{card.body}</p></div></article>)}</div></div></section>
      {faculty?.length ? <section className="bg-paper py-16 sm:py-24"><div className="site-shell"><p className="section-label">Meet the team</p><h2 className="section-heading mb-10">The people behind <em>the learning.</em></h2><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{faculty.map((member) => <article key={`${member.name}-${member.role}`} className="overflow-hidden border border-ink/15 bg-[#fffdf7]">{member.photo?.url && <div className="relative aspect-[4/3]"><Image src={member.photo.url} alt={member.photo.alt ?? member.name} fill sizes="(min-width: 1024px) 33vw, 100vw" className="object-cover" /></div>}<div className="p-7"><h3 className="font-display text-2xl font-bold tracking-[-0.04em]">{member.name}</h3><p className="mt-2 font-medium text-olive">{member.role}</p>{member.qualifications && <p className="mt-3 text-sm text-ink-soft">{member.qualifications}</p>}{member.bio && <p className="mt-4 leading-relaxed text-ink-soft">{member.bio}</p>}</div></article>)}</div></div></section> : null}
      <section className="bg-paper py-16 sm:py-24"><div className="site-shell grid gap-10 lg:grid-cols-[0.75fr_1.25fr] lg:gap-24"><div><p className="section-label">{content.panelLabel}</p><h2 className="section-heading">{content.panelTitle} <em>{content.panelAccent}</em></h2></div><div className="border border-ink/15 bg-[#fffdf7] p-8 sm:p-12"><h3 className="font-display text-3xl font-bold tracking-[-0.05em]">{content.panelHeading}</h3><p className="mt-4 text-lg leading-relaxed text-ink-soft">{content.panelBody}</p><div className="mt-8 grid gap-5 sm:grid-cols-2">{content.panelItems.map((item) => <div key={item.title} className="border-t border-ink/15 pt-4"><strong className="block">{item.title}</strong><span className="mt-1 block text-sm leading-relaxed text-ink-soft">{item.body}</span></div>)}</div></div></div></section>
      <section className="bg-ink-deep py-16 text-white sm:py-20"><div className="site-shell flex flex-col items-start justify-between gap-8 lg:flex-row lg:items-center"><h2 className="max-w-3xl font-display text-4xl font-bold tracking-[-0.06em] sm:text-6xl">{content.cta} <em className="font-serif font-normal text-lime">{content.ctaAccent}</em></h2><Link href={content.ctaHref} className="rounded-full bg-lime px-6 py-4 text-sm font-bold text-ink transition hover:-translate-y-0.5">{content.ctaLabel} →</Link></div></section>
    </main>
  )
}
