import { defineField, defineType } from 'sanity'

export const page = defineType({
  name: 'page',
  title: 'Website Page',
  type: 'document',
  fields: [
    defineField({ name: 'title', title: 'Internal title', description: 'Editor-facing name for this page. It may be used to generate the route slug.', type: 'string', validation: (rule) => rule.required() }),
    defineField({ name: 'slug', title: 'Route', description: 'URL segment used to find this page, for example about-us or student.', type: 'slug', options: { source: 'title', maxLength: 96 }, validation: (rule) => rule.required() }),
    defineField({ name: 'seoTitle', title: 'SEO title', description: 'Optional browser and search-result title.', type: 'string' }),
    defineField({ name: 'seoDescription', title: 'SEO description', description: 'Optional search-result summary. Aim for one clear sentence of about 150 characters.', type: 'text', rows: 3 }),
    defineField({ name: 'seoImage', title: 'Social sharing image', description: 'Optional image shown when this page is shared on social media.', type: 'image', options: { hotspot: true }, fields: [defineField({ name: 'alt', title: 'Alternative text', description: 'Describe the social image for accessibility.', type: 'string' })] }),
    defineField({ name: 'heroTitle', title: 'Hero title', description: 'Main heading shown at the top of the page.', type: 'string' }),
    defineField({ name: 'heroAccent', title: 'Hero accent text', description: 'Second line of the hero heading, shown in the accent style.', type: 'string' }),
    defineField({ name: 'heroSummary', title: 'Hero summary', description: 'Short introduction below the hero heading.', type: 'text', rows: 3 }),
    defineField({
      name: 'heroImage',
      title: 'Hero image',
      description: 'Upload or replace the banner image for this page. Use the crop and hotspot controls to choose its focal point.',
      type: 'image',
      options: { hotspot: true },
      fields: [
        defineField({ name: 'alt', title: 'Alternative text', type: 'string', description: 'Describe the image for screen-reader users.' }),
      ],
    }),
    defineField({ name: 'introTitle', title: 'Introduction title', description: 'Main heading for the introduction section.', type: 'string' }),
    defineField({ name: 'introAccent', title: 'Introduction accent text', description: 'Accent portion of the introduction heading.', type: 'string' }),
    defineField({ name: 'introBody', title: 'Introduction paragraphs', description: 'Add one paragraph per item.', type: 'array', of: [{ type: 'text', rows: 4 }] }),
    defineField({ name: 'featureLabel', title: 'Feature section label', description: 'Small label above the feature cards.', type: 'string' }),
    defineField({ name: 'featureTitle', title: 'Feature section title', description: 'Feature cards section heading.', type: 'string' }),
    defineField({ name: 'featureAccent', title: 'Feature section accent', description: 'Accent portion of the feature cards heading.', type: 'string' }),
    defineField({ name: 'cards', title: 'Feature cards', description: 'Cards shown in the feature grid. Add up to three.', type: 'array', of: [{ type: 'featureCard' }], validation: (rule) => rule.max(3) }),
    defineField({ name: 'panelLabel', title: 'Detail section label', description: 'Small label above the detail panel.', type: 'string' }),
    defineField({ name: 'panelTitle', title: 'Detail section title', description: 'Detail panel heading.', type: 'string' }),
    defineField({ name: 'panelAccent', title: 'Detail section accent', description: 'Accent portion of the detail panel heading.', type: 'string' }),
    defineField({ name: 'panelHeading', title: 'Detail panel heading', description: 'Heading inside the bordered detail panel.', type: 'string' }),
    defineField({ name: 'panelBody', title: 'Detail panel description', description: 'Supporting text inside the detail panel.', type: 'text', rows: 4 }),
    defineField({ name: 'panelItems', title: 'Detail panel items', description: 'Short supporting items displayed inside the detail panel.', type: 'array', of: [{ type: 'featureCard' }] }),
    defineField({ name: 'cta', title: 'Call-to-action title', description: 'Closing call-to-action heading.', type: 'string' }),
    defineField({ name: 'ctaAccent', title: 'Call-to-action accent', description: 'Accent portion of the closing heading.', type: 'string' }),
    defineField({ name: 'ctaLabel', title: 'Call-to-action label', description: 'Text shown on the closing button.', type: 'string' }),
    defineField({ name: 'ctaHref', title: 'Call-to-action link', description: 'Internal path or full URL opened by the closing button.', type: 'string' }),
  ],
})
